const fs = require('fs');
const lines = [];
lines.push('// LiveSession - the notebook\'s one live machine (R1 + R2). DOM-free.');
lines.push('import { CPU, Parser, Executor } from \'./engine.mjs\';');
lines.push('import { parseExpects, evaluateExpects } from \'./expect.js\';');
lines.push('import type { ExpectResult, EvalContext } from \'./expect.js\';');
lines.push('import { friendlyErrors } from \'./errors.js\';');
lines.push('import type { FriendlyError } from \'./errors.js\';');
lines.push('');
lines.push('export type CellKind = \'code\' | \'markdown\';');
lines.push('export interface Cell { id: string; kind: CellKind; source: string; }');
lines.push('');
lines.push('export interface RunResult {');
lines.push('  reason: \'cell-end\' | \'halted\' | \'breakpoint\' | \'cap\' | \'left-cell\' | \'reached\' | \'end\' | \'restart-needed\' | \'error\';');
lines.push('  error?: string;');
lines.push('  steps: number;');
lines.push('  output: string;');
lines.push('  regDiff: Record<string, [number, number]>;');
lines.push('  halted: boolean;');
lines.push('  expectResults: ExpectResult[];');
lines.push('  allPassed: boolean;');
lines.push('}');
lines.push('');
lines.push('export interface CellOutput {');
lines.push('  text: string;');
lines.push('  regDiff: Record<string, [number, number]>;');
lines.push('  steps: number;');
lines.push('  reason: RunResult[\'reason\'];');
lines.push('  stale: boolean;');
lines.push('  expectResults: ExpectResult[];');
lines.push('  allPassed: boolean;');
lines.push('}');
lines.push('');
lines.push('export interface LiveState {');
lines.push('  regs: Record<string, number>;');
lines.push('  flags: Record<string, number>;');
lines.push('  cursor: { cellId: string | null; line: number | null; instrIndex: number } | null;');
lines.push('  halted: boolean;');
lines.push('  needsRestart: boolean;');
lines.push('  totalInstrs: number;');
lines.push('}');
lines.push('');
lines.push('const REG_LIST = [\'AX\', \'BX\', \'CX\', \'DX\', \'SI\', \'DI\', \'BP\', \'SP\'];');
lines.push('');
lines.push('function diffRegs(before, after) {');
lines.push('  const d = {};');
lines.push('  for (const k of Object.keys(after)) {');
lines.push('    if ((before[k] ?? 0) !== (after[k] ?? 0)) d[k] = [before[k] ?? 0, after[k] ?? 0];');
lines.push('  }');
lines.push('  return d;');
lines.push('}');
lines.push('');
lines.push('export class LiveSession {');
lines.push('  constructor() {');
lines.push('    this.cells = [];');
lines.push('    this.cpu = new CPU();');
lines.push('    this.ex = new Executor();');
lines.push('    this.outputs = new Map();');
lines.push('    this.needsRestart = false;');
lines.push('    this.built = false;');
lines.push('    this.parsed = null;');
lines.push('    this.starts = [];');
lines.push('    this.lineOwner = [];');
lines.push('    this.bpSource = new Set();');
lines.push('    this.breakpoints = new Set();');
lines.push('    this.expectsByCell = new Map();');
lines.push('    this.cellBase = 0x100;');
lines.push('  }');
fs.writeFileSync('C:/Users/HP/Documents/GitHub/ASMBOOK/src/kernel/session.ts', lines.join('\n'));
console.log('part1 OK');
